app:
  customer:
    save:
      message: Customer saved successfully
    default:
      gender: M
  code: 1001
  cache:
    enable: true
  product:
    default:
      discount: 25.9
  notification:
    emails: email1@gamil.com,email2@gmail.com







